% handles any streamline of processing. Can send tasks to spock
% put functions is seperate sections with their vars
function [job_id_PopulationAnalysis,RecChns]=ProcessingStreamLinePopulationAnalysis(RunonCluster,DateNum,ChNum,AreaNum,PairNum,varargin)
global AnalysisOpts

%SetAnalysisOptions_RuleRepresentation(varargin) % set all of the analysis functions
ParseParams(varargin)

% load clusters
ClusterFunc=ClusterFuncsTemp;
ManData=ManipulateData;
ClusterFunc.CompResource=AnalysisOpts.CompResource;
TrialFunc=TrialFuncs;
SpockPass=AnalysisOpts.SpockPass;
ClusterFunc.username=AnalysisOpts.username;
fprintf('\nSending spock runs for %s',AnalysisOpts.PopulationAna.ProcessingStepNames{AnalysisOpts.ProcessingStep+1});

% EmptyFold=input('Delete out/err folders?(y/n)','s');
% if strcmpi(EmptyFold,'y')
%     ClusterFunc.EmptyOutErrFolders();
% end
[ThisDateNum,RecChns,ThisRecChstxt,NChs]=TrialFunc.GetRecordingChannels(DateNum,AreaNum,ChNum,0);
%% adjust requested run time 
if AnalysisOpts.ProcessingStep<10
    Classifier_TaskSpockTime=ClusterFunc.GetClassifierSpockTime();
elseif AnalysisOpts.ProcessingStep>=10 & AnalysisOpts.ProcessingStep<=16
    GLM_SpockTime=ClusterFunc.GetGLMSpockTime();
elseif AnalysisOpts.ProcessingStep==17
    TDR_SpockTime=ClusterFunc.GetTDRSpockTime();
end
% if we are enforcing a specific time on processing 
if ~isnan(AnalysisOpts.EnforceSpockTime);
    TDR_SpockTime=AnalysisOpts.EnforceSpockTime;
    Classifier_TaskSpockTime=AnalysisOpts.EnforceSpockTime*ones(1,200);
    GLM_SpockTime=AnalysisOpts.EnforceSpockTime;
end
if isempty(AnalysisOpts.NcoresSpock)
    AnalysisOpts.NcoresSpock=AnalysisOpts.NcoresSpockProcessingStep(AnalysisOpts.ProcessingStep);
end
UpdateClassifierAnalysisOpts(); % add extra inputs to the function 

switch AnalysisOpts.ProcessingStep
    case 0
        %% save important data
        for SpkCntStartFieldName=AnalysisOpts.SpkCntStartFieldNames
            [response_SaveImportantData,job_id_PopulationAnalysis,script_name_SaveImportantData]=ClusterFunc.RunFunctiononCluster('Run_SaveImportantData','SaveImportantData',...
                {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],'[]',...
                '$SLURM_ARRAY_TASK_ID','[]','SpkCntStartFieldName',SpkCntStartFieldName{1},...
                'TrlSpkTimeFieldName','AllTrials','ProcessingStep',AnalysisOpts.Animal},...
                {'%i','%s','%s','%s','%s',"'%s'","'%s'","'%s'","'%s'","'%s'","'%s'"},...
                'RunWithDepenency',0,'Array','1-5','Time',200,'Ncores',7,'password',SpockPass,'RunThisFunc',1);
        end
    case 1
        if  AnalysisOpts.CalShuffleSubspace==0 & AnalysisOpts.CalShuffleAxB==0
            %% Perform population analysis  Step1 Do subspace analysis
            [response_PopulationAnalysis,job_id_PopulationAnalysis,script_name_PopulationAnalysis]=ClusterFunc.RunFunctiononCluster('PopulationAnalysis_CalSubspace',AnalysisOpts.ClassifierFunctiononClust,...
                {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],'[]',[ '[' ClusterFunc.ConvMat2Char(AreaNum) ']' ],...
                PairNum,'SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,...
                'TrlSpkTimeFieldName',AnalysisOpts.TrlSpkTimeFieldName,'ProcessingStep',1,'ZscoreFactorData',AnalysisOpts.ZscoreFactorData,'DetrendFactorData',AnalysisOpts.DetrendFactorData,...
                'RunCrossTemporalClassifer',AnalysisOpts.RunCrossTemporalClassifer,...
                'DividSpockSubspace',AnalysisOpts.DividSpockSubspace,'DividSpockSubspace_Cond','$SLURM_ARRAY_TASK_ID','DividSpockSubspace_TrlRng',[ '[' ClusterFunc.ConvMat2Char(AnalysisOpts.DividSpockSubspace_TrlRng) ']' ],'PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin },...
                {'%i','%s','%s','%s','%i',"'%s'","'%s'","'%s'","'%s'","'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%s',"'%s'",'%s',"'%s'",'%i'},...
                'RunWithDepenency',0,'Array',ClusterFunc.ConvMat2Char(AnalysisOpts.DividSpockSubspace_Cond),'Time',30,'Ncores',1,'Memory',15,'password',...
                SpockPass,'RunThisFunc',1);
        elseif AnalysisOpts.CalShuffleSubspace==1  | AnalysisOpts.CalShuffleAxB==1
            %% Perform population analysis  Step1 Do subspace analysis
            [response_PopulationAnalysis,job_id_PopulationAnalysis,script_name_PopulationAnalysis]=ClusterFunc.RunFunctiononCluster('PopulationAnalysis_CalSubspace_Shuff',AnalysisOpts.ClassifierFunctiononClust,...
                {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],'[]',[ '[' ClusterFunc.ConvMat2Char(AreaNum) ']' ],...
                PairNum,'SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,...
                'TrlSpkTimeFieldName',AnalysisOpts.TrlSpkTimeFieldName,'ProcessingStep',1,'ZscoreFactorData',AnalysisOpts.ZscoreFactorData,'DetrendFactorData',AnalysisOpts.DetrendFactorData,...
                'CalShuffleSubspace',AnalysisOpts.CalShuffleSubspace,'CalShuffleSubspace_Cond','$SLURM_ARRAY_TASK_ID','CalShuffleSubspace_TrlRng',[ '[' ClusterFunc.ConvMat2Char(AnalysisOpts.CalShuffleSubspace_TrlRng) ']' ],'PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin,'CalShuffleAxB',AnalysisOpts.CalShuffleAxB } ,...
                {'%i','%s','%s','%s','%i',"'%s'","'%s'","'%s'","'%s'","'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%s',"'%s'",'%s',"'%s'",'%i',"'%s'",'%i'},...
                'RunWithDepenency',0,'Array',ClusterFunc.ConvMat2Char(AnalysisOpts.CalShuffleSubspace_Cond),'Time',15,'Ncores',3,'Memory',4,'password',...
                SpockPass,'RunThisFunc',1);
        end
        %% plot subspace results
    case 2
        [response_PopulationAnalysis,job_id_PopulationAnalysis,script_name_PopulationAnalysis]=ClusterFunc.RunFunctiononCluster('PopulationAnalysis_PlotSubspace',AnalysisOpts.ClassifierFunctiononClust,...
            {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],'[]',[ '[' ClusterFunc.ConvMat2Char(AreaNum) ']' ],...
            '$SLURM_ARRAY_TASK_ID','SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,...
            'TrlSpkTimeFieldName',AnalysisOpts.TrlSpkTimeFieldName,'ProcessingStep',2,'ZscoreFactorData',AnalysisOpts.ZscoreFactorData,'DetrendFactorData',AnalysisOpts.DetrendFactorData,'PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin },...
            {'%i','%s','%s','%s','%s',"'%s'","'%s'","'%s'","'%s'","'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i'},...
            'RunWithDepenency',AnalysisOpts.RunWithDepenency,'job_id_dep',AnalysisOpts.job_id_dep,'Array',ClusterFunc.ConvMat2Char(PairNum),'Time',20,'Ncores',3,'Memory',4,'password',...
            SpockPass,'RunThisFunc',1);
    case 3
        GetSpockInfo4Tasks(DateNum,ChNum,AreaNum,PairNum,Classifier_TaskSpockTime(PairNum))
        if AnalysisOpts.CalShuffleClassifier==0 & AnalysisOpts.DividSpockClassifier==0
            %% Perform population analysis Step3 Do classification no shuffle and no divide
            [response_PopulationAnalysis,job_id_PopulationAnalysis,script_name_PopulationAnalysis]=ClusterFunc.RunFunctiononCluster('PopulationAnalysis_RunClassifier',AnalysisOpts.ClassifierFunctiononClust,...
                {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],'[]',[ '[' ClusterFunc.ConvMat2Char(AreaNum) ']' ],...
                '$SLURM_ARRAY_TASK_ID','SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,...
                'TrlSpkTimeFieldName',AnalysisOpts.TrlSpkTimeFieldName,'ProcessingStep',3,'ZscoreFactorData',AnalysisOpts.ZscoreFactorData,...
                'DetrendFactorData',AnalysisOpts.DetrendFactorData,'RunCrossTemporalClassifer',AnalysisOpts.RunCrossTemporalClassifer,'PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin,'PopulationAna.MaxMatchTrialConds',AnalysisOpts.PopulationAna.MaxMatchTrialConds,AnalysisOpts.ClassifierLearningParamsFieldsStr },...
                {'%i','%s','%s','%s','%s',"'%s'","'%s'","'%s'","'%s'","'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i'},...
                'RunWithDepenency',AnalysisOpts.RunWithDepenency,'job_id_dep',AnalysisOpts.job_id_dep,'Array',ClusterFunc.ConvMat2Char(PairNum),'Time',500,'Ncores',5,'password',...
                SpockPass,'RunThisFunc',1);
        elseif AnalysisOpts.DividSpockClassifier & AnalysisOpts.CalShuffleClassifier==0            
            if isempty(AnalysisOpts.DividSpockClassifier_Cond);job_id_PopulationAnalysis=[];ReportNull('');return;end
            %% Perform population analysis Step3 Do classification with dividing
            [response_PopulationAnalysis,job_id_PopulationAnalysis,script_name_PopulationAnalysis]=ClusterFunc.RunFunctiononCluster('PopulationAnalysis_RunClassifier',AnalysisOpts.ClassifierFunctiononClust,...
                {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],'[]',[ '[' ClusterFunc.ConvMat2Char(AreaNum) ']' ],...
                PairNum,'SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,...
                'TrlSpkTimeFieldName',AnalysisOpts.TrlSpkTimeFieldName,'ProcessingStep',3,'ZscoreFactorData',AnalysisOpts.ZscoreFactorData,...
                'DetrendFactorData',AnalysisOpts.DetrendFactorData,'RunCrossTemporalClassifer',AnalysisOpts.RunCrossTemporalClassifer,'DividSpockClassifier',AnalysisOpts.DividSpockClassifier,'DividSpockClassifier_Cond','$SLURM_ARRAY_TASK_ID',...
                'DividSpockClassifier_TrlRng',[ '[' ClusterFunc.ConvMat2Char(AnalysisOpts.DividSpockClassifier_TrlRng) ']' ],'PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin,'PopulationAna.MaxMatchTrialConds',AnalysisOpts.PopulationAna.MaxMatchTrialConds,...
                'RunDummyFile',AnalysisOpts.RunDummyFile,'SweepClassifierConds',AnalysisOpts.SweepClassifierConds,'ExchangeableCalShuffClassifier',AnalysisOpts.ExchangeableCalShuffClassifier,'Classifier_Nrep',AnalysisOpts.Classifier_Nrep,AnalysisOpts.ClassifierLearningParamsFieldsStr{:}} ,...
                {'%i','%s','%s','%s','%i',"'%s'","'%s'","'%s'","'%s'","'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%s',"'%s'",'%s',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',AnalysisOpts.ClassifierLearningParamsFieldsSpf{:}},...
                'RunWithDepenency',AnalysisOpts.RunWithDepenency,'job_id_dep',AnalysisOpts.job_id_dep,'Array',ClusterFunc.ConvMat2Char(AnalysisOpts.DividSpockClassifier_Cond),'Time',Classifier_TaskSpockTime(PairNum),'Ncores',3,'password',...
                SpockPass,'RunThisFunc',1);
        elseif AnalysisOpts.CalShuffleClassifier==1
            if isempty(AnalysisOpts.DividSpockClassifier_Cond);job_id_PopulationAnalysis=[];ReportNull('');return;end
            % chunk this into 2500 matrixes max
            [ChunkRuns,FactorChunk]=ManData.ChuckMatValue(AnalysisOpts.DividSpockClassifier_Cond,AnalysisOpts.ChunkMaxArray);
            for Chunk=1:length(ChunkRuns)
                %% Perform population analysis Step3 Do classification shuffle
                [response_PopulationAnalysis,job_id_PopulationAnalysis{Chunk},script_name_PopulationAnalysis]=ClusterFunc.RunFunctiononCluster('PopulationAnalysis_RunClassifier_Shuff',AnalysisOpts.ClassifierFunctiononClust,...
                    {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],'[]',[ '[' ClusterFunc.ConvMat2Char(AreaNum) ']' ],...
                    PairNum,'SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,...
                    'TrlSpkTimeFieldName',AnalysisOpts.TrlSpkTimeFieldName,'ProcessingStep',3,'ZscoreFactorData',AnalysisOpts.ZscoreFactorData,...
                    'DetrendFactorData',AnalysisOpts.DetrendFactorData,'RunCrossTemporalClassifer',AnalysisOpts.RunCrossTemporalClassifer,'CalShuffleClassifier',1,'DividSpockClassifier_Cond','$SLURM_ARRAY_TASK_ID',...
                    'DividSpockClassifier_TrlRng',[ '[' ClusterFunc.ConvMat2Char(AnalysisOpts.DividSpockClassifier_TrlRng) ']' ],'PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin,'PopulationAna.MaxMatchTrialConds',AnalysisOpts.PopulationAna.MaxMatchTrialConds,...
                    'RunDummyFile',AnalysisOpts.RunDummyFile,'ExchangeableCalShuffClassifier',AnalysisOpts.ExchangeableCalShuffClassifier,'Classifier_Nrep',AnalysisOpts.Classifier_Nrep,'DividSpockClassifier',AnalysisOpts.DividSpockClassifier,'ChunkArrayBiasNum',FactorChunk(Chunk),AnalysisOpts.ClassifierLearningParamsFieldsStr{:}} ,...
                    {'%i','%s','%s','%s','%i',"'%s'","'%s'","'%s'","'%s'","'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%s',"'%s'",'%s',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',AnalysisOpts.ClassifierLearningParamsFieldsSpf{:}},...
                    'RunWithDepenency',AnalysisOpts.RunWithDepenency,'job_id_dep',AnalysisOpts.job_id_dep,'Array',ClusterFunc.ConvMat2Char(ChunkRuns{Chunk}),'Time',Classifier_TaskSpockTime(PairNum),'Ncores',AnalysisOpts.NcoresSpock,'password',SpockPass,'RunThisFunc',1);
            end
        end
        
    case 4
        GetSpockInfo4Tasks(DateNum,ChNum,AreaNum,PairNum,Classifier_TaskSpockTime(PairNum))
        if AnalysisOpts.RunCrossTemporalClassifer;NCores=12;else;NCores=8;end
        %% Perform population analysis  Step4 Plot results
        [response_PopulationAnalysis,job_id_PopulationAnalysis,script_name_PopulationAnalysis]=ClusterFunc.RunFunctiononCluster('PopulationAnalysis_PlotClassifier',AnalysisOpts.ClassifierFunctiononClust,...
            {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],'[]',[ '[' ClusterFunc.ConvMat2Char(AreaNum) ']' ],...
            '$SLURM_ARRAY_TASK_ID','SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,...
            'TrlSpkTimeFieldName',AnalysisOpts.TrlSpkTimeFieldName,'ProcessingStep',4,'ZscoreFactorData',AnalysisOpts.ZscoreFactorData,'DetrendFactorData',AnalysisOpts.DetrendFactorData,...
            'PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin,'PopulationAna.MaxMatchTrialConds',AnalysisOpts.PopulationAna.MaxMatchTrialConds,'RunDummyFile',AnalysisOpts.RunDummyFile,...
            'ExchangeableCalShuffClassifier',AnalysisOpts.ExchangeableCalShuffClassifier,'RunCrossTemporalClassifer',AnalysisOpts.RunCrossTemporalClassifer,AnalysisOpts.ClassifierLearningParamsFieldsStr{:}},...
            {'%i','%s','%s','%s','%s',"'%s'","'%s'","'%s'","'%s'","'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',AnalysisOpts.ClassifierLearningParamsFieldsSpf{:}},...
            'RunWithDepenency',AnalysisOpts.RunWithDepenency,'job_id_dep',AnalysisOpts.job_id_dep,'Array',ClusterFunc.ConvMat2Char(PairNum),'Time',Classifier_TaskSpockTime(PairNum),'Ncores',NCores,'Memory',10,'password',...
            SpockPass,'RunThisFunc',1);
    case 5
        %% Perform population analysis  Step5 Comparision
        [response_PopulationAnalysis,job_id_PopulationAnalysis,script_name_PopulationAnalysis]=ClusterFunc.RunFunctiononCluster('PopulationAnalysis_PlotClassifierComparision',AnalysisOpts.ClassifierFunctiononClust,...
            {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],'[]',[ '[' ClusterFunc.ConvMat2Char(AreaNum) ']' ],...
            '$SLURM_ARRAY_TASK_ID','SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,...
            'TrlSpkTimeFieldName',AnalysisOpts.TrlSpkTimeFieldName,'ProcessingStep',5,'ZscoreFactorData',AnalysisOpts.ZscoreFactorData,'DetrendFactorData',AnalysisOpts.DetrendFactorData,...
            'PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin,'PopulationAna.MaxMatchTrialConds',AnalysisOpts.PopulationAna.MaxMatchTrialConds,'RunDummyFile',AnalysisOpts.RunDummyFile,...
            'ExchangeableCalShuffClassifier',AnalysisOpts.ExchangeableCalShuffClassifier,'RunCrossTemporalClassifer',AnalysisOpts.RunCrossTemporalClassifer,AnalysisOpts.ClassifierLearningParamsFieldsStr{:}},...
            {'%i','%s','%s','%s','%s',"'%s'","'%s'","'%s'","'%s'","'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',AnalysisOpts.ClassifierLearningParamsFieldsSpf{:}},...
            'RunWithDepenency',AnalysisOpts.RunWithDepenency,'job_id_dep',AnalysisOpts.job_id_dep,'Array',ClusterFunc.ConvMat2Char(PairNum),'Time',Classifier_TaskSpockTime(PairNum),'Ncores',12,'Memory',10,'password',...
            SpockPass,'RunThisFunc',1);
        
    case 7 % plot subspace analysis
        [response_PopulationAnalysis,job_id_PopulationAnalysis_PS7,script_name_PopulationAnalysis]=ClusterFunc.RunFunctiononCluster('PopulationAnalysis_PlotSubspace',AnalysisOpts.ClassifierFunctiononClust,...
            {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],'[]',[ '[' ClusterFunc.ConvMat2Char(AreaNum) ']' ],...
            '$SLURM_ARRAY_TASK_ID','SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,...
            'TrlSpkTimeFieldName',AnalysisOpts.TrlSpkTimeFieldName,'ProcessingStep',7,'PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin },...
            {'%i','%s','%s','%s','%s',"'%s'","'%s'","'%s'","'%s'","'%s'",'%i',"'%s'",'%i'},...
            'RunWithDepenency',0,'Array',ClusterFunc.ConvMat2Char(PairNum),'Time',60,'Ncores',7 ,'password',...
            SpockPass,'RunThisFunc',1);
    case 8 % concatinate classifier files toghether
        GetSpockInfo4Tasks(DateNum,ChNum,AreaNum,PairNum,Classifier_TaskSpockTime(PairNum))
        if isempty(AnalysisOpts.job_id_dep) && AnalysisOpts.RunWithDepenency==1;job_id_PopulationAnalysis=[];ReportNull('');return;end
        [response_PopulationAnalysis,job_id_PopulationAnalysis,script_name_PopulationAnalysis]=ClusterFunc.RunFunctiononCluster('PopulationAnalysis_ConcatClassifier',AnalysisOpts.ClassifierFunctiononClust,...
            {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],'[]',[ '[' ClusterFunc.ConvMat2Char(AreaNum) ']' ],...
            PairNum,'SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,...
            'TrlSpkTimeFieldName',AnalysisOpts.TrlSpkTimeFieldName,'ProcessingStep',8,'ZscoreFactorData',AnalysisOpts.ZscoreFactorData,...
            'DetrendFactorData',AnalysisOpts.DetrendFactorData,'RunCrossTemporalClassifer',AnalysisOpts.RunCrossTemporalClassifer,'CalShuffleClassifier',AnalysisOpts.CalShuffleClassifier,...
            'PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin ,'PopulationAna.MaxMatchTrialConds',AnalysisOpts.PopulationAna.MaxMatchTrialConds ,'RunDummyFile',AnalysisOpts.RunDummyFile,...
            'DividSpockClassifier',AnalysisOpts.DividSpockClassifier,'ExchangeableCalShuffClassifier',AnalysisOpts.ExchangeableCalShuffClassifier,'DividSpockClassifier_Cond',1,'ReWriteClassifierData',AnalysisOpts.ReWriteClassifierData,...
            AnalysisOpts.ClassifierLearningParamsFieldsStr{:}},...
            {'%i','%s','%s','%s','%i',"'%s'","'%s'","'%s'","'%s'","'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',AnalysisOpts.ClassifierLearningParamsFieldsSpf{:}},...
            'RunWithDepenency',AnalysisOpts.RunWithDepenency,'job_id_dep',AnalysisOpts.job_id_dep,'Array','1','Time',Classifier_TaskSpockTime(PairNum),'Ncores',12,'password',...
            SpockPass,'RunThisFunc',1);
    case 9 % concatinate subspace files
        if isempty(AnalysisOpts.job_id_dep);job_id_PopulationAnalysis=[];ReportNull('');return;end
        [response_PopulationAnalysis,job_id_PopulationAnalysis,script_name_PopulationAnalysis]=ClusterFunc.RunFunctiononCluster('PopulationAnalysis_ConcatSubspace',AnalysisOpts.ClassifierFunctiononClust,...
            {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],'[]',[ '[' ClusterFunc.ConvMat2Char(AreaNum) ']' ],...
            PairNum,'SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,...
            'TrlSpkTimeFieldName',AnalysisOpts.TrlSpkTimeFieldName,'ProcessingStep',9,'ZscoreFactorData',AnalysisOpts.ZscoreFactorData,...
            'DetrendFactorData',AnalysisOpts.DetrendFactorData,'DividSpockSubspace',AnalysisOpts.DividSpockSubspace,'CalShuffleSubspace',AnalysisOpts.CalShuffleSubspace,'PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin,'CalShuffleAxB',AnalysisOpts.CalShuffleAxB },...
            {'%i','%s','%s','%s','%i',"'%s'","'%s'","'%s'","'%s'","'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i'},...
            'RunWithDepenency',AnalysisOpts.RunWithDepenency,'job_id_dep',AnalysisOpts.job_id_dep,'Array','1','Time',600,'Ncores',1,'Memory',20,'password',...
            SpockPass,'RunThisFunc',1);
        %% GLM analysis results
    case 10
        %% generate a summery plot for population or single cells
        [response_SingleCellAnalysis,job_id_PopulationAnalysis,script_name_SingleCellAnalysis]=ClusterFunc.RunFunctiononCluster('Run_SingleCellAnalysis_PlotGLMSummery',AnalysisOpts.ClassifierFunctiononClust,...
            {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],'$SLURM_ARRAY_TASK_ID',[ '[' ClusterFunc.ConvMat2Char(AreaNum) ']' ],'[]','SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,'UseFakeNeurons',AnalysisOpts.UseFakeNeurons,'ProcessingStep',10,'PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin},...
            {'%i','%s','%s','%s','%s',"'%s'","'%s'","'%s'",'%i',"'%s'",'%i',"'%s'",'%i'},...
            'RunWithDepenency',AnalysisOpts.RunWithDepenency,'job_id_dep',AnalysisOpts.job_id_dep,...
            'Array',ThisRecChstxt,'Time',20,'Ncores',10,'password',SpockPass,'RunThisFunc',1);
        
        %          %% plot single cell charactristcs population of neurons
        %         [response_SingleCellAnalysis,job_id_SingleCellAnalysis_PS4,script_name_SingleCellAnalysis]=ClusterFunc.RunFunctiononCluster('Run_SingleCellAnalysis','SingleCellAnalysis',...
        %             {1,[ '[' ClusterFunc.ConvMat2Char(DateNum) ']' ],'[]','$SLURM_ARRAY_TASK_ID','[]','SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,'UseFakeNeurons',AnalysisOpts.UseFakeNeurons,'ProcessingStep',4},...
        %             {'%i','%s','%s','%s','%s',"'%s'","'%s'","'%s'",'%i',"'%s'",'%i'},...
        %             'RunWithDepenency',0,'Array',ClusterFunc.ConvMat2Char(AreaNum),'Time',30,'Ncores',1,'password',SpockPass,'RunThisFunc',0);
        %
    case 11        
        if AnalysisOpts.DividSpockGLM==1 & AnalysisOpts.CalShuffleGLM==0
            if isempty(AnalysisOpts.DividSpockGLM_Cond);job_id_PopulationAnalysis=[];ReportNull('');return;end
            %% fit GLM model to single neurons factor omission method
            [response_SingleCellAnalysis,job_id_PopulationAnalysis,script_name_SingleCellAnalysis]=ClusterFunc.RunFunctiononCluster('Run_SingleCellAnalysis_FitGLM',AnalysisOpts.ClassifierFunctiononClust,...
                {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],'$SLURM_ARRAY_TASK_ID',[ '[' ClusterFunc.ConvMat2Char(AreaNum) ']' ],AnalysisOpts.RunThisGLMmodel,'SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,'UseFakeNeurons',AnalysisOpts.UseFakeNeurons,'ProcessingStep',11,'CalShuffleGLM',0,'DividSpockGLM',1,'DividSpockGLM_Cond',AnalysisOpts.DividSpockGLM_Cond,'PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin},...
                {'%i','%s','%s','%s',"'%s'","'%s'","'%s'","'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i'},...
                'RunWithDepenency',0,'Array',ThisRecChstxt,'Time',GLM_SpockTime,'Ncores',1,'password',SpockPass,'RunThisFunc',1);
        elseif AnalysisOpts.CalShuffleGLM==1
            if isempty(AnalysisOpts.CalShuffleGLM_Cond);job_id_PopulationAnalysis=[];ReportNull('');return;end
            for Ch=1:NChs     
                if ~isempty(AnalysisOpts.CalShuffleGLM_Cond{Ch})
                    %% generate shuffle GLM fits
                    [response_SingleCellAnalysis,job_id_PopulationAnalysis{Ch},script_name_SingleCellAnalysis]=ClusterFunc.RunFunctiononCluster('Run_SingleCellAnalysis_FitShGLM',AnalysisOpts.ClassifierFunctiononClust,...
                        {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],RecChns(Ch),[ '[' ClusterFunc.ConvMat2Char(AreaNum) ']' ],'[]','SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,'UseFakeNeurons',AnalysisOpts.UseFakeNeurons,'ProcessingStep',11,'CalShuffleGLM',1,'DividSpockGLM',0,'CalShuffleGLM_Cond','$SLURM_ARRAY_TASK_ID','PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin},...
                        {'%i','%s','%i','%s','%s',"'%s'","'%s'","'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%s',"'%s'",'%i'},...
                        'RunWithDepenency',0,'Array',ClusterFunc.ConvMat2Char(AnalysisOpts.CalShuffleGLM_Cond{Ch}),'Time',20,'Ncores',1,'password',SpockPass,'RunThisFunc',1);
                end
                if mod(Ch,10)==0;pause(300);end % pause so that we don't overwhenm the spock                 
            end
        end
        %% GLM model comparision pipeline
    case 12
        if AnalysisOpts.SingCellAna.GLMnMdlCompRuns<=100 % if we have more than 100 then send them each individual
            CmpNumTxt=[ '[' ClusterFunc.ConvMat2Char(1:AnalysisOpts.SingCellAna.GLMnMdlCompRuns) ']' ];
            %% fit GLM model to single neurons factor omission method
            [response_SingleCellAnalysis,job_id_PopulationAnalysis,script_name_SingleCellAnalysis]=ClusterFunc.RunFunctiononCluster('Run_SingleCellAnalysis_GLMFitMdlComp',AnalysisOpts.ClassifierFunctiononClust,...
                {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],'$SLURM_ARRAY_TASK_ID',[ '[' ClusterFunc.ConvMat2Char(AreaNum) ']' ],'[]','SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,'UseFakeNeurons',AnalysisOpts.UseFakeNeurons,'ProcessingStep',12,'CalShuffleGLM',0,'DividSpockGLM',1,'DividSpockGLM_Cond',CmpNumTxt,'PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin},...
                {'%i','%s','%s','%s','%s',"'%s'","'%s'","'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%s',"'%s'",'%i'},...
                'RunWithDepenency',0,'Array',ThisRecChstxt,'Time',999,'Ncores',3,'password',SpockPass,'RunThisFunc',1);
        else
            for Ch=1:NChs
                [response_SingleCellAnalysis,job_id_PopulationAnalysis{Ch},script_name_SingleCellAnalysis]=ClusterFunc.RunFunctiononCluster('Run_SingleCellAnalysis_GLMFitMdlComp',AnalysisOpts.ClassifierFunctiononClust,...
                    {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],RecChns(Ch),[ '[' ClusterFunc.ConvMat2Char(AreaNum) ']' ],'[]','SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,'UseFakeNeurons',AnalysisOpts.UseFakeNeurons,'ProcessingStep',12,'CalShuffleGLM',0,'DividSpockGLM',0,'DividSpockGLM_Cond','$SLURM_ARRAY_TASK_ID','PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin},...
                    {'%i','%s','%i','%s','%s',"'%s'","'%s'","'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%s',"'%s'",'%i'},...
                    'RunWithDepenency',0,'Array',ClusterFunc.ConvMat2Char(AnalysisOpts.SingCellAna.GLMnMdlCompRuns),'Time',30,'Ncores',1,'password',SpockPass,'RunThisFunc',1);
            end
        end
    case 13
        %% plot GLM model comparision results
        [response_SingleCellAnalysis,job_id_PopulationAnalysis,script_name_SingleCellAnalysis]=ClusterFunc.RunFunctiononCluster('Run_SingleCellAnalysis_PlotGLMFitMdlComp',AnalysisOpts.ClassifierFunctiononClust,...
            {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],'$SLURM_ARRAY_TASK_ID',[ '[' ClusterFunc.ConvMat2Char(AreaNum) ']' ],'[]','SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,'UseFakeNeurons',AnalysisOpts.UseFakeNeurons,'ProcessingStep',13,'PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin},...
            {'%i','%s','%s','%s','%s',"'%s'","'%s'","'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i'},...
            'RunWithDepenency',AnalysisOpts.RunWithDepenency,'job_id_dep',AnalysisOpts.job_id_dep,'DepenencyType','singleton',...
            'Array',ThisRecChstxt,'Time',20,'Ncores',3,'password',SpockPass,'RunThisFunc',1);
    case 14
        %% Creat a summery file for each area ( this is run after all of the jobs for all neurons are done)
        [response_SingleCellAnalysis,job_id_PopulationAnalysis,script_name_SingleCellAnalysis]=ClusterFunc.RunFunctiononCluster('Run_SingleCellAnalysis_GLMsummery',AnalysisOpts.ClassifierFunctiononClust,...
            {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],'[]',[ '[' ClusterFunc.ConvMat2Char(AreaNum) ']' ],'[]','SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,'UseFakeNeurons',AnalysisOpts.UseFakeNeurons,'ProcessingStep',14,'PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin,'ReWriteGLMData',1},...
            {'%i','%s','%s','%s','%s',"'%s'","'%s'","'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i'},...
            'RunWithDepenency',AnalysisOpts.RunWithDepenency,'job_id_dep',AnalysisOpts.job_id_dep,'DepenencyType','singleton',...
            'Array','1','Time',120,'Ncores',10,'password',SpockPass,'RunThisFunc',1);
    case 15
        if isempty(AnalysisOpts.job_id_dep) & AnalysisOpts.RunWithDepenency;job_id_PopulationAnalysis=[];ReportNull('');return;end
        %% Creat a summery file for each neuron
        [response_SingleCellAnalysis,job_id_PopulationAnalysis,script_name_SingleCellAnalysis]=ClusterFunc.RunFunctiononCluster('Run_SingleCellAnalysis_GLMsummerySing',AnalysisOpts.ClassifierFunctiononClust,...
            {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],'$SLURM_ARRAY_TASK_ID',[ '[' ClusterFunc.ConvMat2Char(AreaNum) ']' ],'[]','SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,'UseFakeNeurons',AnalysisOpts.UseFakeNeurons,'ProcessingStep',15,'CalShuffleGLM',0,'DividSpockGLM',1,'DividSpockGLM_Cond',1,'PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin},...
            {'%i','%s','%s','%s','%s',"'%s'","'%s'","'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i'},...
            'RunWithDepenency',0,'Array',ThisRecChstxt,'Time',GLM_SpockTime,'Ncores',1,'password',SpockPass,'RunThisFunc',1);
    case 16
     %% plot GLM results for area
     [response_SingleCellAnalysis,job_id_PopulationAnalysis,script_name_SingleCellAnalysis]=ClusterFunc.RunFunctiononCluster('Run_SingleCellAnalysis_PlotGLMSummeryArea',AnalysisOpts.ClassifierFunctiononClust,...
         {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],[ '['  ']' ],'$SLURM_ARRAY_TASK_ID','[]','SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,'UseFakeNeurons',AnalysisOpts.UseFakeNeurons,'ProcessingStep',16,'PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin},...
         {'%i','%s','%s','%s','%s',"'%s'","'%s'","'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i'},...
         'RunWithDepenency',AnalysisOpts.RunWithDepenency,'job_id_dep',AnalysisOpts.job_id_dep,'DepenencyType','singleton',...
         'Array',ClusterFunc.ConvMat2Char(AreaNum),'Time',GLM_SpockTime,'Ncores',3,'password',SpockPass,'RunThisFunc',1);
    case 17 
        if isempty(AnalysisOpts.RunThisGLMmodel)
            TaskorMdlName=PairNum;
        else
            TaskorMdlName=AnalysisOpts.RunThisGLMmodel;
        end
        [response_TDRAnalysis,job_id_PopulationAnalysis,script_name_TDRAnalysis]=ClusterFunc.RunFunctiononCluster('Run_TDRAnalysis',AnalysisOpts.ClassifierFunctiononClust,...
            {1,[ '[' ClusterFunc.ConvMat2Char(ThisDateNum) ']' ],[ '['  ']' ],[ '[' ClusterFunc.ConvMat2Char(AreaNum) ']' ],TaskorMdlName,'DividSpockClassifier_Cond','$SLURM_ARRAY_TASK_ID',...
            'SpkCntStartFieldName',AnalysisOpts.SpkCntStartFieldName,'UseFakeNeurons',AnalysisOpts.UseFakeNeurons,...
            'ProcessingStep',17,'CalShuffleGLM',0,'DividSpockGLM',1,'DividSpockGLM_Cond',1,...
            'PopulationAna.PSTHbin',AnalysisOpts.PopulationAna.PSTHbin,AnalysisOpts.ClassifierLearningParamsFieldsStr{:}},...
            {'%i','%s','%s','%s',"'%s'","'%s'",'%s',"'%s'","'%s'","'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",'%i',"'%s'",...
            '%i',"'%s'",'%i',AnalysisOpts.ClassifierLearningParamsFieldsSpf{:}},'RunWithDepenency',AnalysisOpts.RunWithDepenency,'job_id_dep',AnalysisOpts.job_id_dep,'Array', ...
            ClusterFunc.ConvMat2Char(AnalysisOpts.DividSpockClassifier_Cond),'Time',TDR_SpockTime,'Ncores',AnalysisOpts.NcoresSpock,'password',SpockPass,'RunThisFunc',1);
end


% for Rec=1:length(ThisRecs)
%     % get the channels for this recording
%     if isempty(ChNum)
%         [RecChns]=ManData.RunFuncOnRec(TrialFunc,'FindWantedSpkChSet',ThisRecs(Rec),{[AnalysisOpts.SpikeQuality2Look],AraeName},3);
%     else
%         RecChns=ChNum;
%     end
%     NChs=length(RecChns{1});
%     ThisRecChstxt=ClusterFunc.ConvMat2Char(1:NChs);
%
%
% end

%% current runs for classifer
% ProcessingStreamLinePopulationAnalysis(0, 'SilasRecs', [], 1, [])
% ProcessingStreamLinePopulationAnalysis(0, 'SilasRecs', [], 1, [],'TrlSpkTimeFieldName','ToSwitch')
% ProcessingStreamLinePopulationAnalysis(0, 'SilasRecs', [], 1, [],'TrlSpkTimeFieldName','FromSwitch')
ReportNull(job_id_PopulationAnalysis)

end
function ReportNull(x)
if isempty(x);fprintf(2,'NULL:NOT SENT');end
end
function GetSpockInfo4Tasks(DateNum,ChNum,AreaNum,PairNum,Time)
global AnalysisOpts
if sum(AnalysisOpts.ProcessingStep==[3 4 8])
    AnalysisOpts.Spock_TaskName=AnalysisOpts.CurrentClassifierOpts.Name;
    AnalysisOpts.Spock_ExtraInfo=sprintf('%s-%i-%s-%i-%i-%i',AnalysisOpts.AreaNames{AreaNum},...
        AnalysisOpts.PopulationAna.PSTHbin,AnalysisOpts.SpkCntStartFieldName(1:4),...
        AnalysisOpts.DividSpockClassifier,Time,AnalysisOpts.NTrlStpLearningArea);
end
end
function UpdateClassifierAnalysisOpts() % if you want to add new inputs to the classifier opts use this function 
global AnalysisOpts
% add the name of the input and its values in this cell array
AnalysisOpts.ClassifierLearningParamsFieldsStr={'MaxTrlTestLearningArea',AnalysisOpts.MaxTrlTestLearningArea,...
    'Classifier_TrlShuff_LoadObservedClassifierSpecs',AnalysisOpts.Classifier_TrlShuff_LoadObservedClassifierSpecs,...
    'ntrlPerCondTestArea',AnalysisOpts.ntrlPerCondTestArea,...
    'ntrlPerCondArea',AnalysisOpts.ntrlPerCondArea,...
    'NTrlRngTrainLearningArea',AnalysisOpts.NTrlRngTrainLearningArea,...
    'NTrlRngTestLearningArea',AnalysisOpts.NTrlRngTestLearningArea,...
    'LimitFromSwitchPerfArea',AnalysisOpts.LimitFromSwitchPerfArea,...
    'ReWriteClassifierData',AnalysisOpts.ReWriteClassifierData,...
    'CalShuffTrlOrderClassifier',AnalysisOpts.CalShuffTrlOrderClassifier,...
    'GetOnlyShuffLabelsClassifier',AnalysisOpts.GetOnlyShuffLabelsClassifier,...
    'pvalClassifierAnalysis_ClusterCorrect',AnalysisOpts.pvalClassifierAnalysis_ClusterCorrect,...
    'NTrlStpLearningArea',AnalysisOpts.NTrlStpLearningArea,...
    'NeuResamplingSubPopSize',AnalysisOpts.NeuResamplingSubPopSize,...
    'Classifier_TrlShuff_GenClassifierSpecs',AnalysisOpts.Classifier_TrlShuff_GenClassifierSpecs,...
    'CalShuffTrlOrderClassifier_RunAllTrlRng',AnalysisOpts.CalShuffTrlOrderClassifier_RunAllTrlRng,...
    'EqualizeTrialsXConds',AnalysisOpts.EqualizeTrialsXConds,...
    'Subtract4TrialRange',AnalysisOpts.Subtract4TrialRange,...
    'IncludeAllClassifierInfo',AnalysisOpts.IncludeAllClassifierInfo,...
    'Classifier_NrepShuf',AnalysisOpts.Classifier_NrepShuf,...
    'Classifier_NrepShufperFold',AnalysisOpts.Classifier_NrepShufperFold,...
    'Classifier_TrlShuff_ShuffMethod',AnalysisOpts.Classifier_TrlShuff_ShuffMethod,...
    'Classifier_TrlShuff_TrialSet',AnalysisOpts.Classifier_TrlShuff_TrialSet,...    
    'Classifier_FileDateTimeTh',char(AnalysisOpts.Classifier_FileDateTimeTh),...
    'ClassifierNameExtra',AnalysisOpts.ClassifierNameExtra};

% add the type of the input in this cell array
AnalysisOpts.ClassifierLearningParamsFieldsSpf=[repmat({"'%s'",'%i'},1,length(AnalysisOpts.ClassifierLearningParamsFields)+6),...
    repmat({"'%s'","'%s'"},[1 4])];
end




