function [net,outputs] = ClusterSelfOrganizingMapMotif(MotifDistMatrix,varargin)
%CLUSTERSELFORGANIZINGMAPMOTIF Summary of this function goes here
% uses SOM to cluster motif data
% inputs
% MotifDistMatrix: 
% N by N distance matrix of temporal cross correlation between motifs 

% Detailed explanation goes here

% Solve a Clustering Problem with a Self-Organizing Map
% Script generated by NCTOOL

% Sina Tafazoli timeless

inputs = MotifDistMatrix;

% set up options 
opts.dimension1 = 10;
opts.dimension2 = 10;
opts = ParseOptionalInputs(opts,varargin);

% Create a Self-Organizing Map

net = selforgmap([opts.dimension1 opts.dimension2]);

% Train the Network
[net,tr] = train(net,inputs);
% 
% % Test the Network
outputs = net(inputs);
% 
% % View the Network
% view(net)
% 
% % Plots
% % Uncomment these lines to enable various plots.
% figure, plotsomtop(net)
% figure, plotsomnc(net)
% figure, plotsomnd(net)
% figure, plotsomplanes(net)
% figure, plotsomhits(net,inputs)
% figure, plotsompos(net,inputs)
end

