function [fitresult,gof]=FitLogistic(x,y)

ft = fittype( 'L./(1+exp(-k*(x-x0)))', 'independent', {'x'}, 'dependent', 'y','coefficients',{'L','k','x0'});
fo = fitoptions('Method','NonlinearLeastSquares',...
               'Lower',[0,0,0],...
               'Upper',[Inf,Inf,Inf],...
               'StartPoint',rand(1,3));
[fitresult,gof] = fit( x, y, ft,fo );
