%% look at resutls for Axis decocidng 
% we have two conditions CalShuffTrlOrderClassifier_RunAllTrlRng=5 which is
% only for 1-10 and 7:16 and CalShuffTrlOrderClassifier_RunAllTrlRng=0 which is for 1-10 and 64:73
Learning.ExtraConds={'Classifier_Nrep',250,'DividSpockClassifier',3,'RunDummyFile',0,...
    'ReWriteClassifierData',1,'ThisIsSinaPC',1,'pvalClassifierAnalysis_ClusterCorrect',0.001,...
    'ClassifierFunctiononClust','PopulationAnalysisTemp'};%,'Enforce_nCondsRun_Shuff',{[1001]}};

Classifier_NrepShufperFold=250;
Classifier_NrepShuf=50;
Learning.StrTime={'SAMPLE_ON'};
Learning.Conditions={'3D_AxisDecodingSupp'};%'Learning3D_AxisDecoding'};
Learning.Area=1;

GenerateAllFiguresPipeline('Classifier','ALL',Learning.Area,2,100,{'Learning'},Learning.Conditions,Learning.StrTime,...
    Learning.ExtraConds{:},'SweepClassifierConds',0,'CalShuffTrlOrderClassifier',1,'RunMode2',2,...
    'Classifier_NrepShufperFold',Classifier_NrepShufperFold,'Classifier_NrepShuf',Classifier_NrepShuf,...
    'Classifier_TrlShuff_ShuffMethod','RND','Classifier_TrlShuff_TrialSet','FL',...
    'Classifier_TrlShuff_GenClassifierSpecs',1,'CalShuffTrlOrderClassifier_RunAllTrlRng',5,...
    'Subtract4TrialRange',0,'IncludeAllClassifierInfo',0);

for Area=1:5
    Learning.Area=Area;
    PopulationAnalysisTemp(0, 0, [], Learning.Area, Learning.Conditions{1}, 'ProcessingStep',4, ...
        'IncludeAllClassifierInfo',0, ...
        'SweepClassifierConds',0,'CalShuffTrlOrderClassifier',0,'RunMode2',2,...
        'Classifier_TrlShuff_ShuffMethod','RND','Classifier_TrlShuff_TrialSet','FL',...
        'Classifier_TrlShuff_GenClassifierSpecs',0,'CalShuffTrlOrderClassifier_RunAllTrlRng',5,...
        'Subtract4TrialRange',0,'IncludeAllClassifierInfo',0);
end