Alt=load('AltFEFResp.mat');
Same=load('sAMEFEFResp.mat');
Alt
AltCol=Alt{2};
AltCol=Alt.MetricValsDim_Avg(2);
SameCol=Same.MetricValsDim_Avg(2);
Diff=mean(SameCol,2)-mean(AltCol,2)
AltCol
AltCol=Alt.MetricValsDim_Avg(2){1};
Diff=mean(SameCol{1},2)-mean(AltCol{1},2)
Diff<0
sum(diff<0)
sum(Diff<0)/251
1/251
mean(Diff)